domain: chiara-phillips.github.io
url: https://chiara-phillips.github.io
baseurl: ""

title: Chiara Phillips
author: Chiara Phillips

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#

header_pages:
  - index.md
  - tags.md

rrss:
  linkedin: "https://www.linkedin.com/in/chiaraphillips/"
  instagram: "https://www.instagram.com/chiaramphillips/"
  bluesky: "https://bsky.app/profile/chiaraphillips.bsky.social"
  github: "https://github.com/chiara-phillips"
