domain: chiara-phillips.github.io
url: https://chiara-phillips.github.io
baseurl: ""

title: Chiara Phillips
author: Chiara Phillips

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  linkedin: "https://www.linkedin.com/in/chiaraphillips/"
  bluesky: "https://bsky.app/profile/chiaraphillips.bsky.social"
