domain: chiara-phillips.github.io
url: https://chiara-phillips.github.io
baseurl: ""

# GitHub repository information
repository: chiara-phillips/chiara-phillips.github.io

title: Chiara Phillips
author: Chiara Phillips

lang: en

# Disable the default theme
theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-maplibre

color: "#13ccf9"
# disqus:
#   shortname: example-com
#

header_pages:
  - index.md

rrss:
  linkedin: "https://www.linkedin.com/in/chiaraphillips/"
  bluesky: "https://bsky.app/profile/chiaraphillips.bsky.social"
  github: "https://github.com/chiara-phillips"

maplibre:
  width: 100%
  height: 600
  zoom: 1
  center: [0, 90]
  pmtiles: false
  style: "/assets/maps/voyager-gl-style.json"
  sources:
    carto: 
      type: vector
      url: "https://tiles.basemaps.cartocdn.com/vector/carto.streets/v1/tiles.json"
      attribution: © <a href='https://openstreetmap.org'>OpenStreetMap contributors</a>
